//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book_tbl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Book_tbl()
        {
            this.learningMaterial_tbl = new HashSet<learningMaterial_tbl>();
            this.Matching_tbl = new HashSet<Matching_tbl>();
            this.request_tbl = new HashSet<request_tbl>();
        }
    
        public int BookId { get; set; }
        public string BookName { get; set; }
        public Nullable<int> parentBookId { get; set; }
        public Nullable<double> bookpayment { get; set; }
        public string Bookinfo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<learningMaterial_tbl> learningMaterial_tbl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Matching_tbl> Matching_tbl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<request_tbl> request_tbl { get; set; }
    }
}
