//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class learningMaterial_tbl
    {
        public int learnerId { get; set; }
        public int bookId { get; set; }
        public Nullable<int> amount { get; set; }
    
        public virtual Book_tbl Book_tbl { get; set; }
        public virtual learners_tbl learners_tbl { get; set; }
    }
}
