//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class learners_tbl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public learners_tbl()
        {
            this.learningMaterial_tbl = new HashSet<learningMaterial_tbl>();
            this.Matching_tbl = new HashSet<Matching_tbl>();
        }
    
        public int learnerId { get; set; }
        public string learnerName { get; set; }
        public string learnerEmail { get; set; }
        public string gender { get; set; }
        public Nullable<int> occuptionId { get; set; }
        public Nullable<bool> sosRequests { get; set; }
        public Nullable<System.DateTime> startDate { get; set; }
        public Nullable<System.DateTime> endDate { get; set; }
        public Nullable<int> groupId { get; set; }
        public Nullable<bool> wantsToJoin { get; set; }
        public string password { get; set; }
        public Nullable<bool> reminder { get; set; }
    
        public virtual closedGroup_tbl closedGroup_tbl { get; set; }
        public virtual occuption_tbl occuption_tbl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<learningMaterial_tbl> learningMaterial_tbl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Matching_tbl> Matching_tbl { get; set; }
    }
}
