//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BTProjectEntities : DbContext
    {
        public BTProjectEntities()
            : base("name=BTProjectEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Book_tbl> Book_tbl { get; set; }
        public virtual DbSet<closedGroup_tbl> closedGroup_tbl { get; set; }
        public virtual DbSet<learners_tbl> learners_tbl { get; set; }
        public virtual DbSet<learningMaterial_tbl> learningMaterial_tbl { get; set; }
        public virtual DbSet<Matching_tbl> Matching_tbl { get; set; }
        public virtual DbSet<occuption_tbl> occuption_tbl { get; set; }
        public virtual DbSet<request_tbl> request_tbl { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<time_tbl> time_tbl { get; set; }
    }
}
