//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class request_tbl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public request_tbl()
        {
            this.closedGroup_tbl = new HashSet<closedGroup_tbl>();
            this.Matching_tbl = new HashSet<Matching_tbl>();
        }
    
        public int reqId { get; set; }
        public string donorName { get; set; }
        public string donorEmail { get; set; }
        public string reqPurpose { get; set; }
        public int BookId { get; set; }
        public Nullable<int> timeId { get; set; }
        public Nullable<System.DateTime> reqStartDate { get; set; }
        public Nullable<System.DateTime> reqEndDate { get; set; }
        public Nullable<double> payment { get; set; }
        public Nullable<int> occuptionId { get; set; }
        public string genderid { get; set; }
        public string password { get; set; }
        public string extraInfo { get; set; }
        public Nullable<System.DateTime> RegisterEndDate { get; set; }
    
        public virtual Book_tbl Book_tbl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<closedGroup_tbl> closedGroup_tbl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Matching_tbl> Matching_tbl { get; set; }
        public virtual occuption_tbl occuption_tbl { get; set; }
        public virtual time_tbl time_tbl { get; set; }
    }
}
